name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: self-hosted
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: docker up
        run: |
          docker compose up --build -d
          